# Funding options for this project
# Uncomment and fill in the appropriate platforms

# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ["https://example.com/sponsor"]
