export {
  initDatabase,
  getDatabase,
  saveScore,
  getModuleScores,
  getLatestModuleScore,
  getAllModuleScores,
  saveQuestionAttempt,
  getQuestionAttempts,
  getMostMissedQuestions,
  getSetting,
  setSetting,
  getOverallProgress,
  clearAllData,
  exportDatabase,
} from './database';
